version: '3.8'
services:
  api-server:
    build: ./api-server
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      API_SERVER_PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend-server:
    build: ./frontend-server
    environment:
      FRONTEND_SERVER_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - api-server

  mysql:
    image: mysql:8.0
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - project_data:/var/lib/mysql

volumes:
  project_data:
