version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: postdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: postdb
